---
- name: Create VMs
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Create demo VPC
      community.digitalocean.digital_ocean_vpc:
        state: present
        name: demo
        region: "{{ region }}"
        ip_range: 10.66.0.0/24
      register: vpc

    - name: Set VPC UUID
      ansible.builtin.set_fact:
        vpc_uuid: "{{ vpc.data.vpc.id }}"

    - name: Create a new Droplet
      community.digitalocean.digital_ocean_droplet:
        oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
        name: "{{ item }}"
        region_id: "{{ region }}"
        size: "{{ vm_size }}"
        image_id: "{{ vm_image }}"
        private_networking: true
        vpc_uuid: "{{ vpc_uuid }}"
        ssh_keys: "{{ ssh_keys }}"
        unique_name: true
        wait_timeout: 500
        tags:
          - consul_server
          - database
      with_items: "{{ db_hosts }}"

- name: Patroni
  hosts: all
  tasks:
    - name: Wait 600 seconds for target connection to become reachable/usable
      ansible.builtin.wait_for_connection:
