---
- name: Remove VMs
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Remove VMs
      community.digitalocean.digital_ocean_droplet:
        oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
        name: "{{ item }}"
        unique_name: true
        state: absent
        wait_timeout: 500
      with_items: "{{ db_hosts }}"

    - name: Sleep to make shure all VMs are deleted.
      ansible.builtin.pause:
        seconds: 5

    - name: Remove VPC
      community.digitalocean.digital_ocean_vpc:
        state: absent
        name: demo
