---
name: ci

"on":
  - pull_request_target
  - push

permissions: write-all

env:
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          lfs: true

      - uses: actions/cache@v4
        with:
          path: |
            **/public
            **/resources
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - uses: actions/setup-node@v4

      - name: Run yarn install
        uses: borales/actions-yarn@v5
        with:
          cmd: install # will run `yarn install` command

      - name: Build
        run: yarn run full_build

      - name: Deploy to Netlify (dev)
        if: github.ref != 'refs/heads/master'
        uses: nwtgck/actions-netlify@v3.0
        id: netlify
        with:
          publish-dir: "./dist"
          production-deploy: false
          github-deployment-environment: "dev"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        timeout-minutes: 1

      - name: Deploy to Netlify (prod)
        if: github.ref == 'refs/heads/master'
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: "./dist"
          production-deploy: true
          github-deployment-environment: "prod"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        timeout-minutes: 1
